### ISSUE TITLE
Cannot install 1.1.0

### ISSUE THREAD

**Issue by jprusch** [muratbayan/mattermost-file-blocker#8]
Plugin cannot be installed. Tried windows app & web. Error message in UI: Invalid response from server. Other plugins install w/o problem.

Server: Mattermost 6.1.0 Debian / MySQL

**Comment by muratbayan** [comment]
Hi @jprusch 

I suspect that might be related to the maximum file size setting on your Mattermost server
Mattermost have added ARM support for deployment and as a result the plugin is bigger in size and is right now just over 50MB

The default FileSettings.MaxFileSize setting in Mattermost happens to be 50MB...

Are you able to increase this setting (to something like  `"MaxFileSize": 104857600,` for example)?

Let me know if that resolves the issue

**Comment by muratbayan** [comment]
Hi @jprusch 

I suspect that might be related to the maximum file size setting on your Mattermost server
Mattermost have added ARM support for deployment and as a result the plugin is bigger in size and is right now just over 50MB

The default FileSettings.MaxFileSize setting in Mattermost happens to be 50MB...

Are you able to increase this setting (to something like  `"MaxFileSize": 104857600,` for example)?

Let me know if that resolves the issue

**Comment by jprusch** [comment]
Hi @muratbayan

it wasn't the Mattermost server, but the Nginx proxy blocking client uploads > 50 MB. Thanks for pointing in the right direction...

Best regards!
